name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # jalan otomatis tiap hari jam 00:00 UTC
  workflow_dispatch:       # bisa jalan manual juga

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name:   SamAscend
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
